# Table of Contents
 <p>

In [1]:
def my_function(x):
    pass

In [2]:
def my_sq(x):
    return x ** 2

In [3]:
assert my_sq(2) == 4

In [4]:
import pandas as pd

In [5]:
df = pd.DataFrame({
    'a': [10, 20, 30],
    'b': [20, 30, 40]
})

In [6]:
df

a   b
0  10  20
1  20  30
2  30  40

In [7]:
df['a'] ** 2

0    100
1    400
2    900
Name: a, dtype: int64

In [8]:
my_sq

<function __main__.my_sq(x)>

In [9]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [10]:
def my_exp(x, e):
    return x ** e

In [11]:
df['a'].apply(my_exp, e=4)

0     10000
1    160000
2    810000
Name: a, dtype: int64

In [12]:
df

a   b
0  10  20
1  20  30
2  30  40

In [13]:
def print_me(x):
    print(x)

In [14]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [15]:
def avg_3(x, y, z):
    return(x + y + z) / 3

In [16]:
df.apply(avg_3)

TypeError: ("avg_3() missing 2 required positional arguments: 'y' and 'z'", 'occurred at index a')

In [17]:
import numpy as np

In [18]:
def avg_3_apply(col):
    return np.mean(col)

In [19]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [20]:
df.apply(np.mean)

a    20.0
b    30.0
dtype: float64

In [21]:
def avg_3(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return(x + y + z) / 3

In [22]:
(df['a'] + df['b']) / 2

0    15.0
1    25.0
2    35.0
dtype: float64

In [23]:
df

a   b
0  10  20
1  20  30
2  30  40

In [24]:
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN # np.nan or np.NAN
    else:
        return (x + y) / 2

In [25]:
avg_2_mod(20, 100)

nan

In [26]:
avg_2_mod(5, 10)

7.5

In [27]:
avg_2_mod(df['a'], df['b'])

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [28]:
import numpy as np

In [29]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [30]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [31]:
@np.vectorize
def avg_2_mod(x, y):
    if (x == 20):
        return np.NaN # np.nan or np.NAN
    else:
        return (x + y) / 2

In [32]:
avg_2_mod(df['a'], df['b'])

array([15., nan, 35.])

In [33]:
import numba

In [34]:
@numba.vectorize
def avg_2_mod_numbda(x, y):
    if (x == 20):
        return np.NaN # np.nan or np.NAN
    else:
        return (x + y) / 2

In [35]:
avg_2_mod_numbda(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [36]:
def avg_2(x, y):
    """Python function
    """
    return (x + y) / 2

In [37]:
%%timeit
avg_2(df['a'], df['b'])

453 µs ± 22.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [38]:
%%timeit
# vectorize numpy
avg_2_mod(df['a'], df['b'])

201 µs ± 8.59 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [39]:
%%timeit
# vectorize numba
avg_2_mod_numbda(df['a'].values, df['b'].values)

8.24 µs ± 532 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
